%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': 'white',
      'primaryTextColor': 'black',
      'primaryBorderColor': 'black',
      'lineColor': 'black'
    }
  }
}%%

classDiagram

`Object.prototype` <|-- `Iterator.prototype`
`Iterator.prototype` <|-- `GeneratorFunction.prototype.prototype`
`GeneratorFunction.prototype.prototype` <|-- `genFunc.prototype`
`genFunc.prototype` <|-- `genFunc()`

`Object.prototype` <|-- `Function.prototype`
`Function.prototype` <|-- `GeneratorFunction.prototype`
`GeneratorFunction.prototype` <|-- genFunc

`Function.prototype` <|-- Function
Function <|-- GeneratorFunction

genFunc <.. `genFunc()` : instanceof
`genFunc.prototype` "prototype" <-- genFunc
`GeneratorFunction.prototype.prototype` "prototype" <-- `GeneratorFunction.prototype`
`GeneratorFunction.prototype.prototype` --> "constructor" `GeneratorFunction.prototype`
`GeneratorFunction.prototype` "prototype" <-- GeneratorFunction
`GeneratorFunction.prototype` --> "constructor" GeneratorFunction
`Function.prototype` "prototype" <-- Function
`Function.prototype` --> "constructor" Function

class `Object.prototype` {
  __proto__

  hasOwnProperty()
  isPrototypeOf()
  propertyIsEnumerable()
  toLocaleString()
  toString()
  valueOf()
}
class `Iterator.prototype` {
  \[@@iterator]()
}
class `GeneratorFunction.prototype.prototype` {
  <<Generator.prototype>>
  [@@toStringTag] = "Generator"
  next()
  return()
  throw()
}

class genFunc["function* genFunc() {}"] {
  length = 0
  name = "genFunc"
}
class `Function.prototype` {
  \[@@hasInstance]()
  apply()
  bind()
  call()
}
class `GeneratorFunction.prototype` {
  [@@toStringTag] = "GeneratorFunction"
}
class GeneratorFunction {
  length = 1
  name = "GeneratorFunction"
}
class Function {
  length = 1
  name = "Function"
}

link `Object.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
link `Iterator.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator"
link `GeneratorFunction.prototype.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator"
link `Function.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
link `GeneratorFunction.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction"
link GeneratorFunction "/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction"
link Function "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
