%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': 'white',
      'primaryTextColor': 'black',
      'primaryBorderColor': 'black',
      'lineColor': 'black'
    }
  }
}%%

classDiagram

`Object.prototype` <|-- `AsyncIterator.prototype`
`AsyncIterator.prototype` <|-- `AsyncGeneratorFunction.prototype.prototype`
`AsyncGeneratorFunction.prototype.prototype` <|-- `genFunc.prototype`
`genFunc.prototype` <|-- `genFunc()`

`Object.prototype` <|-- `Function.prototype`
`Function.prototype` <|-- `AsyncGeneratorFunction.prototype`
`AsyncGeneratorFunction.prototype` <|-- genFunc

`Function.prototype` <|-- Function
Function <|-- AsyncGeneratorFunction

genFunc <.. `genFunc()` : instanceof
`genFunc.prototype` "prototype" <-- genFunc
`AsyncGeneratorFunction.prototype.prototype` "prototype" <-- `AsyncGeneratorFunction.prototype`
`AsyncGeneratorFunction.prototype.prototype` --> "constructor" `AsyncGeneratorFunction.prototype`
`AsyncGeneratorFunction.prototype` "prototype" <-- AsyncGeneratorFunction
`AsyncGeneratorFunction.prototype` --> "constructor" AsyncGeneratorFunction
`Function.prototype` "prototype" <-- Function
`Function.prototype` --> "constructor" Function

class `Object.prototype` {
  __proto__

  hasOwnProperty()
  isPrototypeOf()
  propertyIsEnumerable()
  toLocaleString()
  toString()
  valueOf()
}
class `AsyncIterator.prototype` {
  \[Symbol.asyncIterator]()
}
class `AsyncGeneratorFunction.prototype.prototype` {
  <<AsyncGenerator.prototype>>
  [Symbol.toStringTag] = "AsyncGenerator"
  next()
  return()
  throw()
}

class genFunc["function* genFunc() {}"] {
  length = 0
  name = "genFunc"
}
class `Function.prototype` {
  \[Symbol.hasInstance]()
  apply()
  bind()
  call()
}
class `AsyncGeneratorFunction.prototype` {
  [Symbol.toStringTag] = "AsyncGeneratorFunction"
}
class AsyncGeneratorFunction {
  length = 1
  name = "AsyncGeneratorFunction"
}
class Function {
  length = 1
  name = "Function"
}

link `Object.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
link `AsyncIterator.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator"
link `AsyncGeneratorFunction.prototype.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator"
link `Function.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
link `AsyncGeneratorFunction.prototype` "/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGeneratorFunction"
link AsyncGeneratorFunction "/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGeneratorFunction"
link Function "/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
