%%{init: { "sequence": { "wrap": true, "width":250, "noteAlign": "center", "messageAlign": "center" }} }%%


sequenceDiagram
    participant Client
    participant Server

    Note left of Client: Request with a stale cache. The validators are used a preconditions for the request.
    Client->>Server: GET /doc HTTP/1.1<br/>If-Modified-Since: date<br/>If-None-Match: "abc"
    Note right of Server: Resource changed. Respond with a new version of the resource.
    Server->>Client: HTTP/1.1 200 OK<br/>Last-Modified: date-2<br/>Etag: "xyz"
