%%{init: { "sequence": { "wrap": true, "width":250, "noteAlign": "center", "messageAlign": "center" }} }%%

sequenceDiagram
    participant Client
    participant Server

    Note left of Client: Initial request. The cache is empty and the request is not conditional
    Client->>Server: GET /doc HTTP/1.1
    Note right of Server: Resource returned<br>Both validators are set
    Server->>Client: HTTP/1.1 200 OK<br/>Last-Modified: date<br/>Etag: "xyz"
