%%{init: { "sequence": { "wrap": true, "width":250, "noteAlign": "left", "messageAlign": "center" }} }%%

sequenceDiagram
    participant Client
    participant Server

    Client->>Server: GET /resources/credentialed-content/ HTTP/1.1<br/>Origin: https://foo.example<br/>Cookie: pageAccess=2
    Server->>Client: HTTP/1.1 200 OK<br/>Access-Control-Allow-Origin: https://foo.example<br/>Access-Control-Allow-Credentials: true
