%%{init: { "sequence": { "wrap": true, "width":250, "noteAlign": "left", "messageAlign": "center", "mirrorActors":false  }} }%%

sequenceDiagram
    participant Client as Client<br><br>Origin#58; https#58;//foo.example
    participant Server as Server<br><br>URL#58; https#58;//bar.other

    Client->>Server: GET /resources/public-data/ HTTP/1.1<br/>Origin: https://foo.example
    Server->>Client: HTTP/1.1 200 OK<br/>Access-Control-Allow-Origin: *